#!/bin/bash
# =============================================================================
# 生活保護受給者尊厳支援データベース - バックアップスクリプト
# =============================================================================
#
# 使用方法:
#   ./scripts/backup.sh              # 通常バックアップ
#   ./scripts/backup.sh --full       # フルバックアップ（コンテナ停止あり）
#
# バックアップ先: ./neo4j_backup/
# =============================================================================

set -e

# 設定
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BACKUP_DIR="${PROJECT_DIR}/neo4j_backup"
DATA_DIR="${PROJECT_DIR}/neo4j_data"
CONTAINER_NAME="livelihood-support-neo4j"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

# 色付き出力
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# バックアップディレクトリの作成
mkdir -p "${BACKUP_DIR}"

# 引数チェック
FULL_BACKUP=false
if [ "$1" == "--full" ]; then
    FULL_BACKUP=true
fi

echo "=============================================="
echo "生活保護受給者尊厳支援DB - バックアップ"
echo "=============================================="
echo "日時: $(date)"
echo "プロジェクト: ${PROJECT_DIR}"
echo ""

# コンテナ状態確認
CONTAINER_RUNNING=$(docker ps --filter "name=${CONTAINER_NAME}" --format "{{.Names}}" 2>/dev/null || true)

if [ "$FULL_BACKUP" = true ]; then
    # ===========================================
    # フルバックアップ（コンテナ停止）
    # ===========================================
    log_info "フルバックアップを実行します（コンテナを一時停止）"
    
    BACKUP_FILE="${BACKUP_DIR}/full_backup_${TIMESTAMP}.tar.gz"
    
    # コンテナ停止
    if [ -n "$CONTAINER_RUNNING" ]; then
        log_info "コンテナを停止中..."
        docker stop ${CONTAINER_NAME}
        sleep 3
    fi
    
    # データディレクトリをtar.gzで圧縮
    log_info "データを圧縮中..."
    tar -czf "${BACKUP_FILE}" -C "${PROJECT_DIR}" neo4j_data
    
    # コンテナ再起動
    if [ -n "$CONTAINER_RUNNING" ]; then
        log_info "コンテナを再起動中..."
        docker start ${CONTAINER_NAME}
    fi
    
    # ファイルサイズ
    FILESIZE=$(ls -lh "${BACKUP_FILE}" | awk '{print $5}')
    
    log_info "フルバックアップ完了!"
    echo ""
    echo "  ファイル: ${BACKUP_FILE}"
    echo "  サイズ: ${FILESIZE}"
    
else
    # ===========================================
    # Cypherエクスポート（オンライン）
    # ===========================================
    log_info "Cypherエクスポートを実行します（オンライン）"
    
    if [ -z "$CONTAINER_RUNNING" ]; then
        log_error "コンテナが起動していません。先に起動してください:"
        echo "  cd ${PROJECT_DIR} && docker compose up -d"
        exit 1
    fi
    
    BACKUP_FILE="${BACKUP_DIR}/cypher_export_${TIMESTAMP}.cypher"
    
    # Cypherでノードとリレーションをエクスポート
    log_info "データをエクスポート中..."
    
    docker exec ${CONTAINER_NAME} cypher-shell -u neo4j -p password \
        "CALL apoc.export.cypher.all(null, {format: 'plain', stream: true}) YIELD cypherStatements RETURN cypherStatements" \
        2>/dev/null | grep -v "cypherStatements" | grep -v "^$" > "${BACKUP_FILE}" || {
        
        # APOCが使えない場合は手動エクスポート
        log_warn "APOCエクスポートに失敗。手動エクスポートを試行..."
        
        # ノードのエクスポート
        echo "// Neo4j Backup - ${TIMESTAMP}" > "${BACKUP_FILE}"
        echo "// Generated by livelihood-support backup script" >> "${BACKUP_FILE}"
        echo "" >> "${BACKUP_FILE}"
        
        # 各ラベルのノードをエクスポート
        for label in CasePattern Recipient CaseRecord NgApproach EffectiveApproach MentalHealthStatus EconomicRisk MoneyManagementStatus DailyLifeSupportService CollaborationRecord KeyPerson FamilyMember SupportOrganization MedicalInstitution Certificate AuditLog; do
            docker exec ${CONTAINER_NAME} cypher-shell -u neo4j -p password \
                "MATCH (n:${label}) RETURN n" 2>/dev/null >> "${BACKUP_FILE}" || true
        done
    }
    
    # ファイルサイズ
    FILESIZE=$(ls -lh "${BACKUP_FILE}" | awk '{print $5}')
    
    log_info "Cypherエクスポート完了!"
    echo ""
    echo "  ファイル: ${BACKUP_FILE}"
    echo "  サイズ: ${FILESIZE}"
fi

# 古いバックアップの削除（30日以上前）
log_info "古いバックアップを削除中（30日以上前）..."
find "${BACKUP_DIR}" -name "*.tar.gz" -mtime +30 -delete 2>/dev/null || true
find "${BACKUP_DIR}" -name "*.cypher" -mtime +30 -delete 2>/dev/null || true

# バックアップ一覧
echo ""
echo "=============================================="
echo "現在のバックアップ一覧"
echo "=============================================="
ls -lh "${BACKUP_DIR}"/*.tar.gz "${BACKUP_DIR}"/*.cypher 2>/dev/null || echo "(バックアップファイルなし)"

echo ""
log_info "バックアップ処理が完了しました"
